### ISSUE TITLE
Fungal shifting cursed liquid doesn't work?

### ISSUE THREAD

**Issue by BarclayII** [Conga0/Apotheosis#21]
I tried to collect some cursed liquid and fungal shifting it.  I successfully shifted the liquid into something else (e.g. gunpowder) but the cursed liquid at the edge of a world is still there, except that when I black hole it, it will release gunpowder.  Is this by design?

Another issue: with chemical curiosities mod enabled, even when you bottle cursed liquid and with CheatGUI confirming that the next shift will change the material in the flask (cursed liquid), you cannot fungal shift it.  In my case, CheatGUI said the next shift will be from cursed liquid to blood, but at the end cursed liquid is still there in the bottle.  Since without chemical curiosities mod I can successfully shift cursed liquid, I assume it's a mod compatibility problem.

**Comment by Conga0** [comment]
Cursed Liquid is composed of two different materials, one is a static liquid and the other is a flowing liquid.

I could try looking into making their shifts be synced.

**Comment by Conga0** [comment]
Fixed for the next commit
