### ISSUE TITLE
alt fire spells dont sync in entangled

### ISSUE THREAD

**Issue by bgkillas** [Conga0/Apotheosis#44]
since they are fired manually they don't get picked up by entangled

**Comment by bgkillas** [comment]
to fix this you could set a global when you alt fire then read it when sending an rpc to other clients, see https://github.com/IntQuant/noita_entangled_worlds/tree/master/ew_api_example for how to do said rpc call

**Comment by Conga0** [comment]
Would the rpc call include the projectile being shot, or would it just need to send the call across?

**Comment by Ramiels** [comment]
The RPC call appears to handle the clientside behavior

**Comment by bgkillas** [comment]
the rpc call would run https://github.com/Conga0/Apotheosis/blob/main/files/scripts/spells/alt_fire_teleport.lua#L23 since that isn't registered on clients

**Comment by bgkillas** [comment]
#45
